# backend/agents/prompts/vc_memo_prompt.py

VC_MEMO_SYSTEM_PROMPT = """
You are the VC Memo Agent for PitchIQ.

You write world-class investor memos in the style of top-tier venture capital firms.
Your memos are read by partners at Sequoia, a16z, Accel, and Lightspeed.
Every section must be crisp, evidence-backed, and compelling.
You write for sophisticated investors who have seen thousands of pitches.
Do not use filler language. Every sentence must earn its place.
Format as clean, professional markdown.
"""

VC_MEMO_USER_TEMPLATE = """
Generate a complete VC-ready Investor Memo using all the research below.

STARTUP PROFILE:
{profile}

MARKET RESEARCH:
{market_research}

FUNDING INTELLIGENCE:
{funding_intelligence}

Write a complete Investor Memo with ALL of these sections:

# [Startup Name] — Investor Memo
*Confidential | {date}*

## Executive Summary
(3-4 sentences: what they do, market size, why now, ask)

## The Problem
(Specific, quantified pain point. Who suffers? How much does it cost them?)

## The Solution
(Clear product description. How it works. Key features. Why better.)

## Market Opportunity
### TAM
### SAM  
### SOM
(Use the market research figures. Show methodology.)

## Business Model
(How they make money. Unit economics if inferable. Pricing strategy.)

## Competitive Landscape
(Table or list of competitors. Clear differentiation. Moat analysis.)

## Traction & Milestones
(State current stage. Key milestones to hit. If pre-launch, describe beta/pilot plan.)

## Team
(Note: Based on provided description. Recommend founder add team bios.)

## Financial Projections
(Conservative 3-year outlook based on market data and comparable companies.)

## Risks & Mitigations
(4-6 real risks with specific mitigations. Don't sugarcoat.)

## Investment Thesis
(Why this wins. What has to be true. Why now.)

## The Ask
(Funding amount, use of funds breakdown, key milestones this round achieves.)

## Conclusion
(Why invest. The upside case. The downside protection.)

---
*This memo was generated by PitchIQ AI. Founders should verify all market data independently.*
"""