"""Add new column

Revision ID: e26abcbd89fa
Revises: b3a2f29c38a8
Create Date: 2026-06-26 16:23:31.595519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e26abcbd89fa'
down_revision: Union[str, None] = 'b3a2f29c38a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_memo_results_confidence_score', table_name='memo_results')
    op.drop_index('ix_memo_results_created_at', table_name='memo_results')
    op.drop_index('ix_memo_results_job_id', table_name='memo_results')
    op.drop_table('memo_results')
    op.drop_index('ix_memo_jobs_created_at', table_name='memo_jobs')
    op.drop_index('ix_memo_jobs_status', table_name='memo_jobs')
    op.drop_index('ix_memo_jobs_status_created', table_name='memo_jobs')
    op.drop_index('ix_memo_jobs_updated_at', table_name='memo_jobs')
    op.drop_table('memo_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('startup_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('agent_progress', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('length(id::text) = 36', name='check_id_length'),
    sa.PrimaryKeyConstraint('id', name='memo_jobs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_memo_jobs_updated_at', 'memo_jobs', ['updated_at'], unique=False)
    op.create_index('ix_memo_jobs_status_created', 'memo_jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_memo_jobs_status', 'memo_jobs', ['status'], unique=False)
    op.create_index('ix_memo_jobs_created_at', 'memo_jobs', ['created_at'], unique=False)
    op.create_table('memo_results',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('startup_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target_users', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('geography', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('market_research_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('funding_analysis_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('memo_markdown', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['memo_jobs.id'], name='memo_results_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='memo_results_pkey'),
    sa.UniqueConstraint('job_id', name='memo_results_job_id_key')
    )
    op.create_index('ix_memo_results_job_id', 'memo_results', ['job_id'], unique=False)
    op.create_index('ix_memo_results_created_at', 'memo_results', ['created_at'], unique=False)
    op.create_index('ix_memo_results_confidence_score', 'memo_results', ['confidence_score'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('api_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###
